[project]
name = "calculator"
version = "1.0.0"
description = "Pons calculator"
dependencies = [
    "flask",
    "sympy"
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"